### ISSUE TITLE
As a DevOps, I would like to manage user access for our system apps through Github

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#14]
I would like to manage user access for grafana, vault and argocd using github authentication.

TODO : 
- [x] Configure SSO for ArgoCD. Will be done in this [issue.](https://github.com/orgs/ai-cfia/projects/7/views/9?pane=issue&itemId=50181799)
- [x]  Configure SSO for Vault. Will be done in this [issue](https://github.com/orgs/ai-cfia/projects/7/views/9?pane=issue&itemId=53896666). 
- [x] #64

**Comment by rngadam** [comment]
Shouldn't this be: 

"As a DevOps, I would like to manage user access to our infrastructure using Github authentication"

...and then have a checklist for the services you want supported? hopefully it's a single solution (on the nginx http frontend?) instead of a solution that requires changes to each service?

**Comment by ThomasCardin** [comment]
ArgoCD Github authentication will be done with this issue https://github.com/ai-cfia/howard/issues/20

**Comment by ThomasCardin** [comment]
Done

To test SSO login see

https://argocd.inspection.alpha.canada.ca/
https://grafana.inspection.alpha.canada.ca/
https://vault.inspection.alpha.canada.ca/
